*** Variables ***
${ID}                          id=RZCWB0Y0DRB
${PLATFORM}                    Android
${NUMBER}                      14
${PACKAGE}                     sk.fourq.ordo.chrien.dealer
${ACTIVITY}                    sk.fourq.ordo.chrien.dealer.StartupActivity
${URL_APPIUM_SERVER}           http://localhost:4725/wd/hub
${UI_VIEWER}                   Uiautomator2

${PACKAGE_AquaTrend}           sk.fourq.ordo.aquatrend.dealer
${AquaTrend_ACTIVITY}          sk.fourq.ordo.aquatrend.dealer.MainActivity
${Corner}                      sk.fourq.ordo.corner.dealer
${Corner_ACTIVITY}             sk.fourq.ordo.activity.MainActivity

# sk.fourq.ordo.aquatrend.dealer/sk.fourq.ordo.aquatrend.dealer.MainActivity

