*** Variables ***
${server_address}    xpath=//android.widget.EditText[@text,'Adresa Ordo servera'];
${input_server_address}   xpath=//android.widget.EditText[@text,'https://Adresa Ordo servera']
${login_name}       xpath=//android.widget.EditText[@text,'Prihlasovacie meno'];
${login_password}   xpath=//android.widget.EditText[@text,'Prihlasovacie heslo'];
${login_button}     xpath=//android.widget.Button[@text,'Uložiť nastavenia'];